name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login --username ${{ github.repository_owner }} --password ${{ secrets.GH_ACCESS_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/${{ github.repository_owner }}/solax-cloud-prometheus-exporter:latest
          docker push ghcr.io/${{ github.repository_owner }}/solax-cloud-prometheus-exporter:latest
