name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: login to ghcr
        run: |
          docker login --username ${{ github.repository_owner }} --password ${{ secrets.GH_ACCESS_TOKEN }} ghcr.io
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        run: |
         docker buildx build --push \
          --tag ghcr.io/davidprokopec/solax-cloud-prometheus-exporter:latest \
          --platform linux/amd64,linux/arm64 .
